# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'
    
    encoders: 
        Symfony\Component\Security\Core\User\User: plaintext
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
    
    # require ROLE_ADMIN for /Competences/create*
    - { path: ^/Competences/create, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Competences/edit*
    - { path: ^/Competences/edit, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Competences/remove*
    - { path: ^/Competences/remove, roles: ROLE_ADMIN }
  
    # require ROLE_ADMIN for /Loisirs/create*
    - { path: ^/Loisirs/create, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Loisirs/edit*
    - { path: ^/Loisirs/edit, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Loisirs/remove*
    - { path: ^/Loisirs/remove, roles: ROLE_ADMIN }

    # require ROLE_ADMIN for /Experience/create*
    - { path: ^/Experience/create, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Experience/edit*
    - { path: ^/Experience/edit, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Experience/remove*
    - { path: ^/Experience/remove, roles: ROLE_ADMIN }

    # require ROLE_ADMIN for /Formation/create*
    - { path: ^/Formation/create, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Formation/edit*
    - { path: ^/Formation/edit, roles: ROLE_ADMIN }
    
    # require ROLE_ADMIN for /Formation/remove*
    - { path: ^/Formation/remove, roles: ROLE_ADMIN }